# Generated by Django 5.0.6 on 2024-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iddata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='date_of_issue',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='district_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='id_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='place_of_issue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iddata',
            name='serial_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
