# Generated by Django 5.0.6 on 2024-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0002_iddata_date_of_birth_iddata_date_of_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iddata',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='iddata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='iddata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iddata',
            name='place_of_issue',
        ),
        migrations.AddField(
            model_name='iddata',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iddata',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='iddata',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='district_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='id_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
