# Generated by Django 5.0.6 on 2024-05-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0005_alter_iddata_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
