# Generated by Django 4.1 on 2024-05-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0007_alter_iddata_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_cc', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
                ('axles', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
