# Generated by Django 5.0.6 on 2024-08-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0009_payslipdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslipdata',
            old_name='nett_pay',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='payslipdata',
            old_name='station',
            new_name='net_pay',
        ),
    ]
