# Generated by Django 5.0.6 on 2024-09-02 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0011_rename_tax_pin_payslipdata_kra_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_tenure', models.CharField(blank=True, max_length=100, null=True)),
                ('id_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idapp.iddata')),
                ('payslip_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idapp.payslipdata')),
            ],
        ),
    ]
