# Generated by Django 5.0.6 on 2024-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0013_remove_loanapplicationdata_loan_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationdata',
            name='id_data',
        ),
        migrations.RemoveField(
            model_name='loanapplicationdata',
            name='payslip_data',
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='loan_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='loan_tenure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
