# Generated by Django 5.0.6 on 2024-09-02 12:31

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0014_remove_loanapplicationdata_id_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogBookData',
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='id_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idapp.iddata', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='loanapplicationdata',
            name='payslip_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idapp.payslipdata', null=True, blank=True),
        ),
    ]
