# Generated by Django 5.0.6 on 2024-09-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0015_delete_logbookdata_loanapplicationdata_id_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='id_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idapp.iddata'),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='payslip_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idapp.payslipdata'),
        ),
    ]
