# Generated by Django 5.0.6 on 2024-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0016_alter_loanapplicationdata_id_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
