# Generated by Django 5.0.6 on 2024-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0017_alter_loanapplicationdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='loan_amount',
            field=models.CharField(blank=True, default='0.00', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationdata',
            name='loan_tenure',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
