# Generated by Django 5.0.6 on 2024-09-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0018_alter_loanapplicationdata_loan_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplicationData',
        ),
    ]
