# Generated by Django 4.1 on 2024-10-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0020_loanapplicationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='commuter_allowance',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='hardship_allowance',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='payroll_number',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='rental_house_allowance',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='total_deductions',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='total_earnings',
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='bank_branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='designation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='disability_exemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='employment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='id_num',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='pf_num',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='retirement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='tax_pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idapp.employerdata'),
        ),
    ]
