# Generated by Django 5.1.2 on 2024-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0022_alter_payslipdata_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipdata',
            name='basic_salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='commuter_allowance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='rental_house_allowance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='total_deductions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslipdata',
            name='total_earnings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
