# Generated by Django 5.1.2 on 2024-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0024_alter_payslipdata_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceTypes',
            fields=[
                ('allowance_type', models.AutoField(primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(null=True)),
                ('allowance_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact_details', models.CharField(max_length=100, null=True)),
                ('other_info', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employerdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='payslipdata',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='employerdata',
            name='bank_branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='designation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='disability_exemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='employer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='employment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='id_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='pf_num',
            field=models.CharField(default=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerdata',
            name='retirement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerdata',
            name='tax_pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
