# Generated by Django 5.1.2 on 2024-10-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idapp', '0025_allowancetypes_designation_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdata',
            name='pf_num',
            field=models.CharField(null=True, unique=True),
        ),
    ]
